#!/bin/bash

meleename="WillsetMelee"
stdname="WillsetS"

# ENSURE SCRIPT IS BEING RUN FROM Bupdate!
# This is because we're copying the files into the directory the script is being run in.
# We do this because we're going to be copying them as sudo later. This way, we know exactly where to look.
dir="$(basename $(pwd))"
[ $dir != "bupdate" ] && echo "Please run bupdate in bupdate directory; see comments for details!" && exit 1

# Evaluate dependency: Git
[ ! -f "$(which git)" ] && echo "Git not installed; please install before continuing." && exit 1 

# WillsetMelee
echo "----- CHECKING WILLSET MELEE -----"
meleepath="$meleename"
if [ ! -d "$meleepath/.git" ]
then
  git clone "git@github.com:Beeciv/$meleename.git"
else 
  cd $meleepath
  git pull
  cd ..
fi

# Standard Willset
echo "----- CHECKING WILLSET STD -----"
stdpath="$stdname"
if [ ! -d "$stdpath/.git" ]
then
  git clone "git@github.com:Beeciv/$stdname.git"
else
  cd $stdpath
  git pull
  cd ..
fi
