#!/bin/bash

# Evaluate dependency: Git
[ ! -f "$(which git)" ] && echo "Git not installed; please install before continuing." && exit 1 

fpath="$HOME/.freeciv"
[ ! -d $fpath ] && echo "Creating Freeciv directory at $fpath" && mkdir "$fpath"

path="$fpath/Willset"
[ ! -d $path ] && echo "Creating Willset directory at $path" && mkdir "$path"

cd $path

# WillsetMelee
echo "----- CHECKING WILLSET MELEE -----"
meleepath="$path/WillsetMelee"
if [ ! -d "$meleepath/.git" ]
then
  git clone git@github.com:Beeciv/WillsetMelee.git
else 
  cd $meleepath
  git pull
  cd $path
fi

# Standard Willset
echo "----- CHECKING WILLSET STD -----"
stdpath="$path/WillsetS"
if [ ! -d "$stdpath/.git" ]
then
  git clone git@github.com:Beeciv/WillsetS.git
else
  cd $stdpath
  git pull
  cd $path
fi
