#!/bin/bash

meleename="WillsetMelee"
stdname="WillsetS"

# Evaluate dependency: Git
[ ! -f "$(which git)" ] && echo "Git not installed; please install before continuing." && exit 1 

# WillsetMelee
echo "----- CHECKING WILLSET MELEE -----"
meleepath="$meleename"
if [ ! -d "$meleepath/.git" ]
then
  git clone "git@github.com:Beeciv/$meleename.git"
else 
  cd $meleepath
  git pull
  cd ..
fi

# Standard Willset
echo "----- CHECKING WILLSET STD -----"
stdpath="$stdname"
if [ ! -d "$stdpath/.git" ]
then
  git clone "git@github.com:Beeciv/$stdname.git"
else
  cd $stdpath
  git pull
  cd ..
fi
