#!/usr/bin/env bash

config="installdirs" # PATH TO INSTALL FILES LIST.
meleename="WillsetMelee"
stdname="WillsetS"

# Validate that copy targets are present.

# $1: directory
# $2: serv file
# $3: name
function validate {  
  if [[ (! -d "$1") || (! -f "$2") ]]
  then
    echo "$3 not present/complete; ensure grab script has been run first."
    exit 1
  fi
}

meleedir="$meleename/$meleename"
meleeserv="$meleename/$meleename.serv"
validate $meleedir $meleeserv $meleename

stddir="$stdname/WillsetS"
stdserv="$stdname/WillsetS.serv"
validate $stddir $stdserv $stdname

# Copies to all present install directories.
# In order to simplify program logic, just ignores not-present directories.
while IFS="" read -r line; do
  if [[ -d $line ]]; then  
    echo "Placing installs in $line"
    cp -r "$meleedir" "$line"
    cp -r "$meleeserv" "$line"
    cp -r "$stddir" "$line"
    cp -r "$stdserv" "$line"
  else
    echo "Install directory $line not present; not copying here."
  fi
done < <(grep -vE '^#|$#' $config)
