#!/usr/bin/env bash

# NOTE: TO CHANGE YOUR INSTALL DIRECTORY, CHANGE THIS VARIABLE!
install="/usr/share/games/freeciv"

meleename="WillsetMelee"
stdname="WillsetS"

fpath="/usr/share/games/freeciv"
[ ! -d "$fpath" ] && echo "Freeciv data directory not present at $fpath. Is freeciv installed?" && exit 1

[ "$(id -u)" != "0" ] && echo "Please run as superuser or files cannot be copied!" && exit 1

# Validation
meleebase="WillsetMelee"
meleedir="$meleebase/WillsetMelee"
meleeserv="$meleebase/WillsetMelee.serv"
if [[ (! -d $meleedir) || (! -f $meleeserv) ]]
then
  echo "$meleename not present/complete; ensure grab script has been run first."
  exit 1
fi

stdbase="WillsetS"
stddir="$stdbase/WillsetS"
stdserv="$stdbase/WillsetS.serv"
if [[ (! -d "$stddir") || (! -f "$stdserv") ]]
then
  echo "$stdname not present/complete; ensure grab script has been run first."
  exit 1
fi

# Copy
echo "Placing rulesets at $install"

cp -r "$meleedir" "$install"
cp -r "$meleeserv" "$install"
cp -r "$stddir" "$install"
cp -r "$stdserv" "$install"
