#!/usr/bin/env bash

config="installdirs" # PATH TO INSTALL FILES LIST.
meleename="WillsetMelee"
stdname="WillsetS"

[ "$(id -u)" != "0" ] && echo "Please run as superuser or files cannot be copied!" && exit 1

# Get install dirs from config file.
installs=""
read -r installs < <(grep -v "^#" $config)

for install in $installs
do
  [ ! -d $install ] && echo "Freeciv data directory not present at $install. Is freeciv installed?" && exit 1
done

# Validation

# $1: directory
# $2: serv file
# $3: name
function validate {  
  if [[ (! -d "$1") || (! -f "$2") ]]
  then
    echo "$3 not present/complete; ensure grab script has been run first."
    exit 1
  fi
}

meleebase="WillsetMelee"
meleedir="$meleebase/WillsetMelee"
meleeserv="$meleebase/WillsetMelee.serv"
validate $meleedir $meleeserv $meleename

stdbase="WillsetS"
stddir="$stdbase/WillsetS"
stdserv="$stdbase/WillsetS.serv"
validate $stddir $stdserv $stdname

# Copy
for install in $installs
do
  echo "Placing installs in $install"
  cp -r "$meleedir" "$install"
  cp -r "$meleeserv" "$install"
  cp -r "$stddir" "$install"
  cp -r "$stdserv" "$install"
done

